---
language: python
python: "3.8"
dist: xenial
sudo: required
services:
  - docker
env:
  - SITE=test.yml

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce

install:
  # Install Ansible.
  - pip install ansible==2.9.13
  - pip install ansible-lint
  - pip install molecule
  - pip install docker

#script:
#  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
